---
- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Restart webapp
  service:
    name: "{{ webapp_service_name }}"
    state: restarted

- name: Restart nginx
  service:
    name: nginx
    state: restarted
    