- hosts: all
  become: yes
  roles:
    - common

- name: Persistent routing på kontroll, DMZ och backend
  hosts: control:dmz:backend
  become: true
  roles:
    - routes

- hosts: gateway
  become: yes
  roles:
    - firewall

- hosts: vault
  become: yes
  roles:
    - vault
    - vault-init
    - vault-secrets

- hosts: database
  become: yes
  roles:
    - database