---
- name: Lägg ut persistent routing via netplan
  template:
    src: 99-static-routes.yaml.j2
    dest: /etc/netplan/99-static-routes.yaml
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Apply netplan