---
# Installerar Python på webservern
# Flask behöver Python för att kunna köras

- name: Installera python3
  apt:
    name: python3
    state: present
    # Installerar Flask för webbapplikationen

- name: Installera python3-flask
  apt:
    name: python3-flask
    state: present
    # Installerar nginx

- name: Installera nginx
  apt:
    name: nginx
    state: present
   # Installerar pip för Python-paket

- name: Installera python3-pip
  apt:
    name: python3-pip
    state: present
     # Skapar katalog för webbapplikationen

- name: Skapa katalog för Flask-applikation
  file:
    path: /opt/webapp
    state: directory
    - name: Start nginx
  service:
    name: nginx
    state: started
    enabled: true
    